=      add  volume 5
-      add  volume -5
left   seek -5     exact
right  seek +5     exact
Q      quit
Ctrl+q quit

q      ignore
s      ignore
S      ignore
Alt+s  ignore
Ctrl+s ignore

# test
/      sub-search
H      history
