=      add  volume 2
-      add  volume -2
left   seek -5     exact
right  seek +5     exact
up seek +30 exact
down seek -30 exact

Q      quit
Ctrl+q quit

Ctrl+= add video-zoom 0.02
Ctrl+- add video-zoom -0.02
Ctrl+0 set video-zoom 0

Alt+-  add audio-delay -0.1
Alt+=  add audio-delay  0.1
Alt+=  add audio-delay  0.1

t script-message-to seek_to toggle-seeker

PGUP  script-binding chapter-prev-or-playlist
PGDWN script-binding chapter-next-or-playlist

q      ignore
s      ignore
S      ignore
Alt+s  ignore
Ctrl+s ignore

# test
/      sub-search
H      history

