=      add  volume 5
-      add  volume -5
left   seek -5     exact
right  seek +5     exact
Q      quit
Ctrl+q quit

PGUP  script-binding chapter-prev-or-playlist
PGDWN script-binding chapter-next-or-playlist

q      ignore
s      ignore
S      ignore
Alt+s  ignore
Ctrl+s ignore

# test
/      sub-search
H      history

