# BIG streaming buffer
cache                  = yes
cache-secs             = 120
cache-on-disk          = no
; cache-dir            = J:\cache\mpv-cache
cache-pause            = no
cache-pause-initial    = no
cache-pause-wait       = 15

; demuxer-max-bytes      = 1GiB
; demuxer-max-back-bytes = 256MiB
; demuxer-lavf-o         = protocol_whitelist = [file,tcp,tls,https,crypto,data]

# network tolerance
stream-lavf-o          = reconnect = 1
stream-lavf-o          = reconnect_streamed = 1
stream-lavf-o          = reconnect_delay_max = 10

vo                     = gpu-next
profile                = gpu-hq

scale                  = ewa_lanczossharp
cscale                 = ewa_lanczossharp
dscale                 = mitchell

; deband                 = yes
; sigmoid-upscaling      = yes

hdr-tone-mapping       = bt.2390
tone-mapping           = bt.2390

# Remember playback position
save-position-on-quit  = yes
save-watch-history     = yes
